package common

var BLACK_TITLE = [] string {
    "访问拒绝","页面不存在", "安全防御", "非法访问", "安全卫士", "非法访问","request rejected", "page error",
    "404 page", "not found", "page 404", "error page", "bad request",
}


var USER_AGENT = [] string {
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/37.0.2062.94 Chrome/37.0.2062.94 Safari/537.36",
    "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36",
    "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko",
    "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:40.0) Gecko/20100101 Firefox/40.0",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/600.8.9 (KHTML, like Gecko) Version/8.0.8 Safari/600.8.9",
    "Mozilla/5.0 (iPad; CPU OS 8_4_1 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12H321 Safari/600.1.4",
    "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36",
    "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10240",
    "Mozilla/5.0 (Windows NT 6.3; WOW64; rv:40.0) Gecko/20100101 Firefox/40.0",
    "Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko",
    "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36",
    "Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko",
    "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:40.0) Gecko/20100101 Firefox/40.0",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/600.7.12 (KHTML, like Gecko) Version/8.0.7 Safari/600.7.12",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:40.0) Gecko/20100101 Firefox/40.0",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/600.8.9 (KHTML, like Gecko) Version/7.1.8 Safari/537.85.17",
    "Mozilla/5.0 (iPad; CPU OS 8_4 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12H143 Safari/600.1.4",
    "Mozilla/5.0 (iPad; CPU OS 8_3 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12F69 Safari/600.1.4",
    "Mozilla/5.0 (Windows NT 6.1; rv:40.0) Gecko/20100101 Firefox/40.0",
}


var BAK_FILES = `
1.7z
1.bak
1.bz2
1.gz
1.rar
1.tar
1.tar.bz2
1.tar.gz
1.tgz
1.war
1.zip
123.7z
123.bak
123.bz2
123.gz
123.rar
123.tar
123.tar.bz2
123.tar.gz
123.tgz
123.war
123.zip
2.7z
2.bak
2.bz2
2.gz
2.rar
2.tar
2.tar.bz2
2.tar.gz
2.tgz
2.war
2.zip
3.7z
3.bak
3.bz2
3.gz
3.rar
3.tar
3.tar.bz2
3.tar.gz
3.tgz
3.war
3.zip
WEB-INF.7z
WEB-INF.bak
WEB-INF.bz2
WEB-INF.gz
WEB-INF.rar
WEB-INF.tar
WEB-INF.tar.bz2
WEB-INF.tar.gz
WEB-INF.tgz
WEB-INF.war
WEB-INF.zip
admin.7z
admin.bak
admin.bz2
admin.gz
admin.rar
admin.tar
admin.tar.bz2
admin.tar.gz
admin.tgz
admin.war
admin.zip
api.7z
api.bak
api.bz2
api.gz
api.rar
api.tar
api.tar.bz2
api.tar.gz
api.tgz
api.war
api.zip
app.7z
app.bak
app.bz2
app.gz
app.rar
app.tar
app.tar.bz2
app.tar.gz
app.tgz
app.war
app.zip
back.7z
back.bak
back.bz2
back.gz
back.rar
back.tar
back.tar.bz2
back.tar.gz
back.tgz
back.war
back.zip
backup.7z
backup.bak
backup.bz2
backup.gz
backup.rar
backup.tar
backup.tar.bz2
backup.tar.gz
backup.tgz
backup.war
backup.zip
beifen.7z
beifen.bak
beifen.bz2
beifen.gz
beifen.rar
beifen.tar
beifen.tar.bz2
beifen.tar.gz
beifen.tgz
beifen.war
beifen.zip
cms.7z
cms.bak
cms.bz2
cms.gz
cms.rar
cms.tar
cms.tar.bz2
cms.tar.gz
cms.tgz
cms.war
cms.zip
conf.7z
conf.bak
conf.bz2
conf.gz
conf.rar
conf.tar
conf.tar.bz2
conf.tar.gz
conf.tgz
conf.war
conf.zip
config.7z
config.bak
config.bz2
config.gz
config.rar
config.tar
config.tar.bz2
config.tar.gz
config.tgz
config.war
config.zip
console.7z
console.bak
console.bz2
console.gz
console.rar
console.tar
console.tar.bz2
console.tar.gz
console.tgz
console.war
console.zip
data.7z
data.bak
data.bz2
data.gz
data.rar
data.tar
data.tar.bz2
data.tar.gz
data.tgz
data.war
data.zip
database.7z
database.bak
database.bz2
database.gz
database.rar
database.tar
database.tar.bz2
database.tar.gz
database.tgz
database.war
database.zip
deploy.7z
deploy.bak
deploy.bz2
deploy.gz
deploy.rar
deploy.tar
deploy.tar.bz2
deploy.tar.gz
deploy.tgz
deploy.war
deploy.zip
download.7z
download.bak
download.bz2
download.gz
download.rar
download.tar
download.tar.bz2
download.tar.gz
download.tgz
download.war
download.zip
home.7z
home.bak
home.bz2
home.gz
home.rar
home.tar
home.tar.bz2
home.tar.gz
home.tgz
home.war
home.zip
htdocs.7z
htdocs.bak
htdocs.bz2
htdocs.gz
htdocs.rar
htdocs.tar
htdocs.tar.bz2
htdocs.tar.gz
htdocs.tgz
htdocs.war
htdocs.zip
html.7z
html.bak
html.bz2
html.gz
html.rar
html.tar
html.tar.bz2
html.tar.gz
html.tgz
html.war
html.zip
info.7z
info.bak
info.bz2
info.gz
info.rar
info.tar
info.tar.bz2
info.tar.gz
info.tgz
info.war
info.zip
install.7z
install.bak
install.bz2
install.gz
install.rar
install.tar
install.tar.bz2
install.tar.gz
install.tgz
install.war
install.zip
login.7z
login.bak
login.bz2
login.gz
login.rar
login.tar
login.tar.bz2
login.tar.gz
login.tgz
login.war
login.zip
manage.7z
manage.bak
manage.bz2
manage.gz
manage.rar
manage.tar
manage.tar.bz2
manage.tar.gz
manage.tgz
manage.war
manage.zip
manager.7z
manager.bak
manager.bz2
manager.gz
manager.rar
manager.tar
manager.tar.bz2
manager.tar.gz
manager.tgz
manager.war
manager.zip
public.7z
public.bak
public.bz2
public.gz
public.rar
public.tar
public.tar.bz2
public.tar.gz
public.tgz
public.war
public.zip
root.7z
root.bak
root.bz2
root.gz
root.rar
root.tar
root.tar.bz2
root.tar.gz
root.tgz
root.war
root.zip
server.7z
server.bak
server.bz2
server.gz
server.rar
server.tar
server.tar.bz2
server.tar.gz
server.tgz
server.war
server.zip
sql.7z
sql.bak
sql.bz2
sql.gz
sql.rar
sql.tar
sql.tar.bz2
sql.tar.gz
sql.tgz
sql.war
sql.zip
sys.7z
sys.bak
sys.bz2
sys.gz
sys.rar
sys.tar
sys.tar.bz2
sys.tar.gz
sys.tgz
sys.war
sys.zip
system.7z
system.bak
system.bz2
system.gz
system.rar
system.tar
system.tar.bz2
system.tar.gz
system.tgz
system.war
system.zip
temp.7z
temp.bak
temp.bz2
temp.gz
temp.rar
temp.tar
temp.tar.bz2
temp.tar.gz
temp.tgz
temp.war
temp.zip
test.7z
test.bak
test.bz2
test.gz
test.rar
test.tar
test.tar.bz2
test.tar.gz
test.tgz
test.war
test.zip
upload.7z
upload.bak
upload.bz2
upload.gz
upload.rar
upload.tar
upload.tar.bz2
upload.tar.gz
upload.tgz
upload.war
upload.zip
war.7z
war.bak
war.bz2
war.gz
war.rar
war.tar
war.tar.bz2
war.tar.gz
war.tgz
war.war
war.zip
web.7z
web.bak
web.bz2
web.gz
web.rar
web.tar
web.tar.bz2
web.tar.gz
web.tgz
web.war
web.zip
webapps.7z
webapps.bak
webapps.bz2
webapps.gz
webapps.rar
webapps.tar
webapps.tar.bz2
webapps.tar.gz
webapps.tgz
webapps.war
webapps.zip
website.7z
website.bak
website.bz2
website.gz
website.rar
website.tar
website.tar.bz2
website.tar.gz
website.tgz
website.war
website.zip
webui.7z
webui.bak
webui.bz2
webui.gz
webui.rar
webui.tar
webui.tar.bz2
webui.tar.gz
webui.tgz
webui.war
webui.zip
www.7z
www.bak
www.bz2
www.gz
www.rar
www.tar
www.tar.bz2
www.tar.gz
www.tgz
www.war
www.zip
wwwroot.7z
wwwroot.bak
wwwroot.bz2
wwwroot.gz
wwwroot.rar
wwwroot.tar
wwwroot.tar.bz2
wwwroot.tar.gz
wwwroot.tgz
wwwroot.war
wwwroot.zip
`
